name: Premier Test

on: [push]   # se dÃ©clenche Ã  chaque push

jobs:
  bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Dis bonjour
        run: echo "ðŸš€ GitHub Actions fonctionne !"

      - name: Liste les fichiers
        run: ls -la